/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type AdminReferrerResponseDto = {
  /** 피추천인 이름 */
  referee: string;
  /** 추천인 이름 */
  referrer: string;
  /** 피추천인 전화번호 */
  referee_phone: string;
  /** 추천인 전화번호 */
  referrer_phone: string;
};
