/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type AdminReservationResponseDto = {
  /** 예약 아이디 */
  id: string;
  /** 출발 위치 */
  pickup_location: string;
  /** 도착 위치 */
  dropoff_location: string;
  /** 예약 일자 */
  created_at: string;
};
