/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type AdminReponseUserDto = {
  /** 유저PK */
  id: number;
  /** 이름 */
  name: string;
  /** 전화번호 */
  phone: string;
  /** 유저ID */
  user_id: string;
  /** 유저역할 */
  role: string;
  /** 티켓수 */
  tickets: number;
  /** 예약수 */
  reservations: number;
  /** 생성일 */
  created_at: string;
  /** 최근로그인일 */
  latest_logined_at: string;
  /** 추천인 */
  referrer: string;
  /** 신원 상태 */
  identity_status: string;
  /** 신원 인증 파일 */
  identity_file: string;
  /** 잔여 추천 횟수 */
  invite_limit: number;
};
