/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type AvailableCarResponseDto = {
  /** 차량 아이디 */
  id: number;
  /** 차량 이름 */
  name: string;
  /** 차량 이미지 */
  image: string;
  /** 차량 좌석 수 */
  seats: number;
  /** 차량 좌석 용량 */
  seat_capacity: number;
  /** 예약 가능한 상태 */
  is_available: boolean;
};
