/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type CarInventoryResponseDto = {
  /** 차량 재고 아이디 */
  id: number;
  /** 차량 재고 상태 */
  status: string;
  /** 차량 재고 번호 */
  registration_number: string;
  /** 차량 재고 생성일 */
  created_at: string;
  /** 차량 재고 수정일 */
  updated_at: string;
};
