/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type CarResponseDto = {
  /** 차량 아이디 */
  id: number;
  /** 차량 이름 */
  name: string;
  /** 차량 이미지 */
  image: string;
  /** 차량 상태 */
  status: string;
  /** 차량 좌석 수 */
  seats: number;
  /** 차량 좌석 용량 */
  seat_capacity: number;
  /** 차량 재고 수 */
  car_inventory_count: number;
  /** 순서 */
  order: number;
};
