/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type CreateTicketDto = {
  /** 유저 아이디 */
  user_id: number;
  /** 티켓 수량 */
  amount: number;
  /** 티켓 만료일 */
  date: number;
};
