/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type CreateDriverDto = {
  /** 이름 */
  name: string;
  /** 전화번호 */
  phone: string;
  /** 주소 */
  address: string;
  /** 고정일정 */
  fixed_schedule: string;
  /** 비고 */
  note: string;
};
