/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type DriverDetailResponseDto = {
  /** 운전자 아이디 */
  id: number;
  /** 운전자 이름 */
  name: string;
  /** 운전자 전화번호 */
  phone: string;
  /** 운전자 주소 */
  address: string;
  /** 운전자 비고 */
  note: string;
  /** 운전자 고정일정 */
  fixed_schedule: string;
};
