/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type ForgotIdDto = {
  /** 이름 */
  name: string;
  /** 전화번호 */
  phone: string;
};
