/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiUsersIdReservationsStatus =
  (typeof GetApiUsersIdReservationsStatus)[keyof typeof GetApiUsersIdReservationsStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiUsersIdReservationsStatus = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  CANCELLED: "CANCELLED",
} as const;
