/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiReservationsStatus } from "./getApiReservationsStatus";

export type GetApiReservationsParams = {
  status: GetApiReservationsStatus;
};
