/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiReservationsAvailableParams = {
  /**
   * 년도
   */
  year: number;
  /**
   * 월
   */
  month: number;
  /**
   * 일
   */
  day: number;
};
