/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type InviteUserDto = {
  /** 초대받을 사람 이름 */
  to_user_name: string;
  /** 초대받을 사람 전화번호 */
  to_user_phone: string;
};
