/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type LatestReservationResponseDto = {
  /** 예약 아이디 */
  id: string;
  /** 출발 시간 */
  pickup_time: string;
  /** 출발 위치 */
  pickup_location: string;
  /** 차량 이름 */
  car_name: string;
};
