/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type LoginDto = {
  /** 아이디 | 카카오 아이디 */
  id?: string;
  /** 비밀번호 */
  password?: string;
};
