/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiAuthLoginHeaders = {
  /**
   * 유저 환경
   */
  "User-Agent"?: string;
};
