/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */
import type { ReferrerResponseDto } from "./referrerResponseDto";

export type ReferrerResponseWithLimitDto = {
  /** 데이터 */
  data: ReferrerResponseDto[];
  /** 초대 가능 횟수 */
  invite_limit: number;
};
