/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type ReferrerResponseDto = {
  /** 피추천인 이름 */
  referee: string;
  /** 추천인 이름 */
  referrer: string;
  /** 생성 일자 */
  created_at: string;
};
