/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */
import type { ViaLocationDto } from "./viaLocationDto";

export type ReservationResponseDto = {
  /** 예약 아이디 */
  id: string;
  /** 예약자 이름 */
  name: string;
  /** 예약자 전화번호 */
  phone: string;
  /** 현재 위치 */
  current_location: string;
  /** 출발 시간 */
  pickup_time: string;
  /** 출발 위치 */
  pickup_location: string;
  /** 경유 위치 */
  via_locations: ViaLocationDto[];
  /** 도착 위치 */
  dropoff_location: string;
  /** 사용 목적 */
  ride_purpose: string;
  /** 짐 개수 */
  luggage_count: number;
  /** 인원 수 */
  passenger_count: number;
  /** 특이사항 */
  special_requests: string;
  /** 차량 이름 */
  car_name: string;
  /** 예약 일자 */
  created_at: string;
};
