/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type ReservationResponseForAdminDto = {
  /** 예약 아이디 */
  id: string;
  /** 예약자 이름 */
  name: string;
  /** 예약자 전화번호 */
  phone: string;
  /** 출발 시간 */
  pickup_time: string;
  /** 출발 위치 */
  pickup_location: string;
  /** 도착 위치 */
  dropoff_location: string;
  /** 차량 이름 */
  car_name: string;
  /** 예약 일자 */
  reserved_date: string;
  /** 운전자 이름 */
  driver: string;
  /** 차량 등록번호 */
  registration_number: string;
  /** 차량 아이디 */
  car_inventory_id: number;
};
