/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type SingUpDto = {
  /** 이름 */
  name: string;
  /** 아이디 | 카카오 아이디 */
  id?: string;
  /** 비밀번호 */
  password?: string;
  /** 전화번호 */
  phone: string;
  /** 추천인 코드 */
  referrerCode: string;
  /** 프로바이더 */
  provider?: string;
};
