/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type TicketResponseDto = {
  /** 티켓 타입 */
  type: string;
  /** 티켓 금액 */
  amount: number;
  /** 이전 티켓 수 */
  prev_tickets: number;
  /** 현재 티켓 수 */
  remaining_tickets: number;
  /** 생성일 */
  created_at: string;
};
