/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCarDtoStatus } from "./updateCarDtoStatus";

export type UpdateCarDto = {
  /** 차량 이름 */
  name?: string;
  /** 차량 이미지 */
  image?: string;
  /** 차량 좌석 수 */
  seats?: number;
  /** 차량 최대 정원 */
  seat_capacity?: number;
  /** 차량 상태 */
  status: UpdateCarDtoStatus;
  /** 순서 */
  order: number;
};
