/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCarInventoryDtoStatus } from "./updateCarInventoryDtoStatus";

export type UpdateCarInventoryDto = {
  /** 차량 등록번호 */
  registration_number: string;
  /** 차량 상태 */
  status: UpdateCarInventoryDtoStatus;
};
