/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAvailableCarsDtoStatus } from "./updateAvailableCarsDtoStatus";

export type UpdateAvailableCarsDto = {
  /** 년도 */
  year: number;
  /** 월 */
  month: number;
  /** 일 */
  day: number;
  /** 차량 아이디 */
  car_id: string;
  /** 차량 상태 */
  status: UpdateAvailableCarsDtoStatus;
};
