/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateReservationDto = {
  /** 예약 상태 */
  status: string;
  /** 운전자 아이디 */
  driver_id: number;
};
