/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateUserDto = {
  /** 이름 */
  name?: string;
  /** 전화번호 */
  phone?: string;
  /** 유저 역할 */
  role: string;
  /** 신원 상태 */
  identity_status: string;
  /** 잔여 추천 횟수 */
  invite_limit: number;
};
