/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 차량 상태
 */
export type UpdateCarDtoStatus =
  (typeof UpdateCarDtoStatus)[keyof typeof UpdateCarDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateCarDtoStatus = {
  AVAILABLE: "AVAILABLE",
  UNAVAILABLE: "UNAVAILABLE",
} as const;
