/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateReservationDtoStatus } from "./updateReservationDtoStatus";

export type UpdateReservationDto = {
  /** 예약 상태 */
  status: UpdateReservationDtoStatus;
  /** 운전자 아이디 */
  driver_id: number;
  /** 차량 인벤토리 아이디 */
  car_inventory_id: number;
};
