/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponseDtoIdentityStatus } from "./userResponseDtoIdentityStatus";

export type UserResponseDto = {
  /** 이름 */
  name: string;
  /** 전화번호 */
  phone: string;
  /** 잔여 티켓 */
  tickets: number;
  /** 운행 횟수 */
  reservations: number;
  /** 티켓 만료일 */
  ticket_expired_at: string;
  /** 신원 상태 */
  identity_status: UserResponseDtoIdentityStatus;
};
