/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Vahana API
 * OpenAPI spec version: 1.0.0
 */

export type ViaLocationDto = {
  /** 경유 위치 */
  location: string;
  /** 경유 시간 */
  time: string;
};
